remote_theme: jekyll/minima

title: 전현준의 기술 블로그
description: 전현준의 기술 블로그입니다.

author:
  name: 전현준
  email: hyunjunian.dev@gmail.com

minima:
  date_format: "%F"

  social_links:
    github: hyunjunian

header_pages:

timezone: Asia/Seoul

url: https://hyunjunian.github.io

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
