remote_theme: jekyll/minima

title: hyunjunian blog
description: hyunjunian의 블로그입니다.

author:
  name: 전현준
  email: hyunjunian.dev@gmail.com

minima:
  date_format: "%F"

  social_links:
    github: hyunjunian

header_pages:
  - 소개.md

timezone: Asia/Seoul

plugins:
  - jekyll-feed
  - jekyll-seo-tag
