remote_theme: jekyll/minima

title: 전현준의 블로그
description: 소프트웨어와 주식에 관련한 유익한 에세이를 읽어보세요.

author:
  name: 전현준
  email: hyunjunian.dev@gmail.com

minima:
  date_format: "%F"

  social_links:
    github: hyunjunian

header_pages:

google_analytics: UA-222099201-1

timezone: Asia/Seoul

url: https://hyunjunian.github.io

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
